### ISSUE TITLE
Support for Wildcard certificate and Docker Image is not accessible

### ISSUE THREAD

**Issue by aronmgv** [henkelmax/traefik-mailcow-certdumper#2]
Hi,

I just migrated from Traefik1 to Traefik2 and looking for solution to get mailcow working again behind it. I came across your image but seems it is not publicly accessible. Would you mind having a look?

CLI output:
```
Pulling certdumper (docker.pkg.github.com/henkelmax/traefik-mailcow-certdumper/traefik-mailcow-certdumper:latest)...
ERROR: Get https://docker.pkg.github.com/v2/henkelmax/traefik-mailcow-certdumper/traefik-mailcow-certdumper/manifests/latest: no basic auth credentials
```

Thanks, Michal

**Comment by aronmgv** [comment]
Tried building from your repo and it errors: 
`certdumper_1  | error: Error dumping certificates: TypeError: Cannot read property 'Certificates' of undefined`

I am using just wildcard certificate:

Traefik2 yml:
```yml
entryPoints:
  websecure:
    address: ':443'
    http:
      tls:
        certResolver: default
        domains:
          - main: example.com
            sans:
              - '*.example.com'
```

certdumper:
```yml
  certdumper:
    #image: 'docker.pkg.github.com/henkelmax/traefik-mailcow-certdumper/traefik-mailcow-certdumper:latest'
    build: ./traefik-mailcow-certdumper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # Used to restart the mailcow services after dumping
      - $PWD/acme/acme.json:/acme.json:ro           # The path to the acme.json
      - /docker/mailcow/data/assets/ssl:/ssl        # The path to the Mailcow ssl directory
    environment:
      ACME_JSON_PATH: "/acme.json"
      DOMAIN: "example.com"
      CERT_PATH: "/ssl/cert.pem"
      KEY_PATH: "/ssl/key.pem"
      RUN_AT_START: "true"
```

Can you please have a look what I might be doing wrong? Thanks, Michal
