### ISSUE TITLE
Cannot read property 'domain' of undefined

### ISSUE THREAD

**Issue by MightyPork** [henkelmax/traefik-mailcow-certdumper#5]
Hi, I'm trying to set this up with latest mailcow and traefik 1.7

```
mailcowdockerized-certdumper-1  | info: CertDumper started
mailcowdockerized-certdumper-1  | info: Domain: 'example.eu'
mailcowdockerized-certdumper-1  | info: ACME JSON path: '/acme.json'
mailcowdockerized-certdumper-1  | info: Certificate path: '/ssl/cert.pem'
mailcowdockerized-certdumper-1  | info: Key path: '/ssl/key.pem'
mailcowdockerized-certdumper-1  | info: File /acme.json changed
mailcowdockerized-certdumper-1  | error: Error dumping certificates: TypeError: Cannot read property 'domain' of undefined
```

Server layout:

```
/srv/mailcow/mailcow-dockerized/
/srv/traefik/acme.json
```

acme.json

```json
{
  "Account": {},
  "Certificates": [
    {
      "Domain": {
        "Main": "example.eu",
        "SANs": [
          "mail.example.eu"
        ]
      },
      "Certificate": "...==",
      "Key": "...=="
    }
  ],
  "HTTPChallenges": {},
  "TLSChallenges": {}
}
```

I have dumper installed like so, in the override file:

```yml
version: '2.1'

services:
  nginx-mailcow:
   ...setup for traefik

  certdumper:
    image: 'henkelmax/traefik-mailcow-certdumper:latest'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Used to restart the mailcow services after dumping
      - "/srv/traefik/acme.json:/acme.json:ro" # The path to the acme.json
      - "/srv/mailcow/mailcow-dockerized/data/assets/ssl:/ssl" # The path to the Mailcow ssl directory
    environment:
      ACME_JSON_PATH: "/acme.json"
      DOMAIN: "example.eu"
      CERT_PATH: "/ssl/cert.pem"
      KEY_PATH: "/ssl/key.pem"
      RUN_AT_START: "true"

networks:
  web:
    external:
      name: traefik
```

traefik.toml

```
defaultEntryPoints = ["http", "https", "ws", "wss"]
InsecureSkipVerify = true

[web]
 address = ":8080"

[entryPoints]
 [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
   entryPoint = "https"

 [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[acme]
 email = "..."
 storage = "acme.json"
 entryPoint = "https"
 onHostRule = true
 onDemand = false

 [acme.httpChallenge]
  entryPoint = "http"
  delayBeforeCheck = 0

 [[acme.domains]]
   main = "example.eu"
   sans = ["mail.example.eu"]

[docker]
 endpoint = "unix:///var/run/docker.sock"
 watch = true

```

any guess what I'm doing wrong? This looks a bit similar to #2
